config/routes.rb
Rails.application.routes.draw do
  get    '/notifications/list',    to: 'notifications#list',    as: 'list_notifications'

  resources :sub_tasks, except: [:new, :edit, :destroy, :show]
  get    '/sub_tasks/new',     to: 'sub_tasks#new',     as: 'new_sub_task'
  get    '/sub_tasks/show',    to: 'sub_tasks#show',    as: 'show_sub_task'
  post   '/sub_tasks/create',  to: 'sub_tasks#create',  as: 'create_sub_task'
  get    '/sub_tasks/edit',    to: 'sub_tasks#edit',    as: 'edit_sub_task'
  patch  '/sub_tasks/update',  to: 'sub_tasks#update',  as: 'update_sub_task'
  delete '/sub_tasks/destroy', to: 'sub_tasks#destroy', as: 'destroy_sub_task'
  
  resources :tasks, except: [:new, :edit, :destroy, :show]
  get    '/tasks/new',     to: 'tasks#new',     as: 'new_task'
  post   '/tasks/create',  to: 'tasks#create',  as: 'create_task'
  get    '/tasks/edit',    to: 'tasks#edit',    as: 'edit_task'
  patch  '/tasks/update',  to: 'tasks#update',  as: 'update_task'
  delete '/tasks/destroy', to: 'tasks#destroy', as: 'destroy_task'
  get    '/tasks/show',    to: 'tasks#show',    as: 'show_task'
  
  resources :milestones, except: [:new, :edit, :destroy, :show]
  get    '/milestones/new',     to: 'milestones#new',     as: 'new_milestone'
  get    '/milestones/show',    to: 'milestones#show',    as: 'show_milestone'
  post   '/milestones/create',  to: 'milestones#create',  as: 'create_milestone'
  get    '/milestones/edit',    to: 'milestones#edit',    as: 'edit_milestone'
  patch  '/milestones/update',  to: 'milestones#update',  as: 'update_milestone'
  delete '/milestones/destroy', to: 'milestones#destroy', as: 'destroy_milestone'

  resources :projects, except: [:new, :edit, :destroy, :show]
  get    '/projects/new',     to: 'projects#new',     as: 'new_project'
  post   '/projects/create',  to: 'projects#create',  as: 'create_project'
  get    '/projects/edit',    to: 'projects#edit',    as: 'edit_project'
  patch  '/projects/update',  to: 'projects#update',  as: 'update_project'
  get    '/projects/destroy', to: 'projects#delete',  as: 'delete_this_project'
  delete '/projects/destroy', to: 'projects#destroy', as: 'destroy_project'
  get    '/projects/show/:id',to: 'projects#show',    as: 'show_project'
  
  get    '/projects/schedule',    to: 'projects#get_schedule',  as: 'get_schedule'
  get    '/projects/budget',      to: 'projects#get_budget',    as: 'get_budget'
  get    '/projects/add_member',  to: 'projects#assign_job',    as: 'assign_member_job'
  post   '/projects/add_member',  to: 'projects#add_member',    as: 'add_member_to_project'
  delete '/projects/lose_member', to: 'projects#remove_member', as: 'remove_member_from_project'
  root to: 'pages#home'

  get '/about', to: 'information#about'

  devise_for :users

  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end
  
  get '/user/:id', to: 'users#show', as: 'show_user'

end

=begin

  Lord of my life
  Here is my heart
  Been so good
  Fear is not my future
  You really are
  Costly
  One name
  Build your church
  More than Able
  Firm Foundation
  Jehovah
  Yahweh
  Yahweh will Manifest
  Yeshua
  Who is this man?
  Praise (Elevation)
  Welcome Resurrection (Elevation)
  Good (can't be anything else)
  Show me your Glory
  Crowned (highlands worship, Rebecca Hart)
  All hail the Power of Jesus name

=end

app/models/milestone.rb
class Milestone < ApplicationRecord
  belongs_to :project
  has_many   :tasks

  validates :name,        presence: true, length: {minimum:  4, maximum:  40}
  validates :description, presence: true, length: {minimum: 10, maximum: 200}
  # validates :completion, size: {maximum: 100}

  def expenses
    tasks = self.tasks
    costs = 0
    tasks.each {|task|
      user = User.find(task.assigned_to)
      rate = user.hourly_rate
      day  = task.start_date
      duration = 1
      (task.end_date - task.start_date).to_i.times do
        day      += 1.day
        duration += 1 if day.on_weekday?
      end
      hours  = duration * 8
      costs += rate * hours
    }
    return costs
  end

  def update_completion
    done  = 0
    self.tasks.each {|task| done += 100 if task.complete == true }
    self.completion = done.to_f/tasks.count
  end
end 

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :logged_in_only
  $project_id = nil

  def new  
    project = Project.find(params[:id].to_i)
    redirect_to show_project_path(id: params[:id]) if current_user.id != project.leader
    @milestone  = Milestone.new
    @project    = Project.find(params[:id].to_i)
    $project_id = params[:id]
  end

  def create
    milestone = Milestone.new
    project   = Project.find($project_id)
    milestone.name        = params[:milestone][:name]
    milestone.description = params[:milestone][:description]
    milestone.budget      = params[:milestone][:budget]
    start_date_parts      = [ params[:milestone][:start_day], params[:milestone][:start_month], params[:milestone][:start_year] ]
    date  = start_date_parts.join("/").to_date
    milestone.start_date  = date if date >= project.start_date

    end_date_parts        = [ params[:milestone][:end_day], params[:milestone][:end_month], params[:milestone][:end_year] ]
    date    = end_date_parts.join("/").to_date
    milestone.end_date    = date if date >= project.start_date

    milestone.baseline_start_date  = start_date_parts.join("/").to_date
    milestone.baseline_end_date    = end_date_parts.join("/").to_date

    milestone.project_id = project.id
    
    if milestone.save
      flash[:notice] = 'Successfully added milestone'
      notification   = Notification.new(project_id: project.id)
      notification.milestone_created_notification(milestone.name)
      notification.save
      redirect_to show_milestone_path(id: milestone.id)
    else
      flash[:alert]  = 'Something went wrong'
      render :new
    end
  end

  def edit
    @milestone = Milestone.find(params[:id])
    @project   = Project.find(@milestone.project_id)
  end

  def update
    milestone = Milestone.find(params[:id])
    milestone.name = params[:milestone][:name]
    milestone.description = params[:milestone][:description]
    milestone.budget      = params[:milestone][:budget]

    days = get_start_and_end_dates_parts
    start_day        = days[:start].join('/').to_date
    end_day          = days[:end].join('/').to_date
    
    if start_day >= milestone.baseline_start_date && start_day < milestone.baseline_end_date
      milestone.start_date = start_day
    end

    if (end_day > milestone.baseline_start_date && end_day <= milestone.baseline_end_date) 
      milestone.end_date = end_day
    end

    if milestone.save
      flash[:notice] = 'Milestone Updated'
      notification   = Notification.new(project_id: milestone.project_id)
      notification.milestone_updated_notification(milestone.name)
      notification.save
      redirect_to show_milestone_path(id: milestone.id)
    else
      flash[:alert]  = 'Something went wrong'
      render :edit
    end
  end

  def destroy
    @milestone = Milestone.find(params[:id])
    @milestone.destroy
    notification = Notification.new(project_id: @milestone.project_id)
    notification.milestone_deleted_notification(@milestone.name)
    notification.save
    flash[:notice] = 'Deleted Milestone'
    redirect_to root_path
  end

  def show
    @milestone = Milestone.find(params[:id].to_i)
    @project   = Project.find(@milestone.project_id)
    @tasks     = Task.where(milestone_id: @milestone.id).order('id DESC')
  end

  private

  def get_start_and_end_dates_parts
    start_day_parts  = [ params[:milestone][:start_day], params[:milestone][:start_month], params[:milestone][:start_year] ]
    end_day_parts    = [ params[:milestone][:end_day],   params[:milestone][:end_month],   params[:milestone][:end_year] ]
    {start: start_day_parts, end: end_day_parts}
  end

end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_form.html.erb
<%= form_with model:@milestone, local: true do |m| %>

  <p> <h4> <%= m.label :Milestone_name %> </h4> </p>
  <%= m.text_field :name, class:'form-control' %>

  <p> <h4> <%= m.label :Milestone_description %> </h4> </p>
  <%= m.text_field :description, class:'form-control' %>

  <div>  
  </div>

  <div class='row mb-4'>
    <p class='mt-4'> <h5>Project dates: ( <%= @project.start_date%> - <%= @project.end_date %> ) </h5> </p>
    <div class='col-6'>
      <h4> <%= m.label  :start_date %> </h4>
      <%= m.select :start_day,   options_for_select(Project.day_options)   %>
      <%= m.select :start_month, options_for_select(Project.month_options) %>
      <%= m.select :start_year,  options_for_select(Project.year_options)  %>
    </div>
    <div class='col-6'>
      <h4> <%= m.label  :end_date %> </h4>
      <%= m.select :end_day,   options_for_select(Project.day_options)   %>
      <%= m.select :end_month, options_for_select(Project.month_options) %>
      <%= m.select :end_year,  options_for_select(Project.year_options)  %>
    </div>
  </div>

  <div>
    <h6> Project budget: <%= @project.budget %> </h6>
    <%= m.label :budget %>
    <%= m.number_field :budget, in: 1000.0..@project.budget, step: 1000.0, class:'form-control mt-2 mb-3'%>
  </div>

  <%= m.submit(@milestone.new_record? ? "Create Milestone" : "Edit Milestone", class:'btn', style:'color: white; background-color: #5c0101') %>
<% end %>
<%= link_to "Cancel", ( @milestone.new_record? ? root_path : show_project_path(id: @project.id) ), class:'btn btn-secondary mt-4 mb-4' %>

<% if !@milestone.new_record? %>
  <div>
    <p><%= link_to "Delete Milestone", destroy_milestone_path(id: @milestone.id), data:{turbo_method: :delete, turbo_confirm: "Delete?"}, class:'btn btn-danger', style:'width:200px;' %></p>
  </div>
<% end %>

app/views/milestones/_page_topper.html.erb
<p>
  <small>
    <small>
      <%= link_to @project.name, show_project_path(id: @project.id), style:'color:white; text-decoration: none' %> >> 
      <% if !@milestone.new_record? %>
        <%= @milestone.name %>
      <% end %>
    </small> 
  </small>
</p>

app/views/milestones/_tasks_list.html.erb
<table class="table" style='color:white'>
  <thead>
    <tr>
      <th scope="col"> <%= @milestone.name %> </th>
      <th scope="col">Complete?</th>
      <th scope="col">Description</th>
      <th scope="col">Assignee</th>      
      <th scope="col">Due Date</th>
    </tr>
  </thead>
  <tbody>
  <% @tasks.each do |t| %>
    <tr>
      <% if t.complete %>
        <td> <%= link_to t.name, show_task_path(id: t.id), style:'color: #29d916; text-decoration: none' %></td>
        <td> complete </td>
      <% else %>
        <td> <%= link_to t.name, show_task_path(id: t.id), style:'color: red; text-decoration: none' %></td>
        <td> incomplete </td>
      <% end %>
      <td> <%= t.description.truncate(40) %> </td>
      <td> <%= User.find(t.assigned_to).email %> </td>
      <td> <%= t.end_date %>  </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/milestones/edit.html.erb
<%= render 'page_topper' %>

<div class='row' style='padding-top:30px'>
  <div class='col-4'></div>
    <div class='col-md-4'>
    <h1>edit Milestone</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/milestones/new.html.erb
<%= render 'page_topper' %>

<div class='row' style='padding-top:30px'>
  <div class='col-4'></div>
    <div class='col-md-4'>
    <h1>New Milestone</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

 

app/views/milestones/show.html.erb
<p>
  <small>
    <small>
      <%= link_to @project.name, show_project_path(id: @project.id), style:'color:white; text-decoration: none' %> >> 
      <%= @milestone.name %>
    </small> 
  </small>
</p>

<div style='margin-left:30px'>
  <div class='row', style='padding-bottom:20px; text-align:justify'>
    <div class='col-md-6' >
      <p> Description:</p> <%= @milestone.description %>
    </div>
  </div>
  <% if @project.leader == current_user.id %>
    <%= link_to "Edit Milestone", edit_milestone_path(id: @milestone.id), class:'btn show_button'%>
  <% end %>
  <hr class='col-md-11'>
  <div class='row' style='margin-left:0px'>
    Tasks List
  </div>
  <% if @project.leader == current_user.id %>
    <%= link_to "New Task", new_task_path(id: @milestone.id), class:'btn mt-4 mb-4 show_button' %>
  <% end %>
  <% if @tasks.present? %>
    <div class='col-md-8'>
      <%= render 'tasks_list' %>
    </div>
  <% end %>
</div>