config/routes.rb
Rails.application.routes.draw do
  get    '/notifications/list',    to: 'notifications#list',    as: 'list_notifications'

  resources :sub_tasks, except: [:new, :edit, :destroy, :show]
  get    '/sub_tasks/new',     to: 'sub_tasks#new',     as: 'new_sub_task'
  get    '/sub_tasks/show',    to: 'sub_tasks#show',    as: 'show_sub_task'
  post   '/sub_tasks/create',  to: 'sub_tasks#create',  as: 'create_sub_task'
  get    '/sub_tasks/edit',    to: 'sub_tasks#edit',    as: 'edit_sub_task'
  patch  '/sub_tasks/update',  to: 'sub_tasks#update',  as: 'update_sub_task'
  delete '/sub_tasks/destroy', to: 'sub_tasks#destroy', as: 'destroy_sub_task'
  
  resources :tasks, except: [:new, :edit, :destroy, :show]
  get    '/tasks/new',     to: 'tasks#new',     as: 'new_task'
  post   '/tasks/create',  to: 'tasks#create',  as: 'create_task'
  get    '/tasks/edit',    to: 'tasks#edit',    as: 'edit_task'
  patch  '/tasks/update',  to: 'tasks#update',  as: 'update_task'
  delete '/tasks/destroy', to: 'tasks#destroy', as: 'destroy_task'
  get    '/tasks/show',    to: 'tasks#show',    as: 'show_task'
  
  resources :milestones, except: [:new, :edit, :destroy, :show]
  get    '/milestones/new',     to: 'milestones#new',     as: 'new_milestone'
  get    '/milestones/show',    to: 'milestones#show',    as: 'show_milestone'
  post   '/milestones/create',  to: 'milestones#create',  as: 'create_milestone'
  get    '/milestones/edit',    to: 'milestones#edit',    as: 'edit_milestone'
  patch  '/milestones/update',  to: 'milestones#update',  as: 'update_milestone'
  delete '/milestones/destroy', to: 'milestones#destroy', as: 'destroy_milestone'

  resources :projects, except: [:new, :edit, :destroy, :show]
  get    '/projects/new',     to: 'projects#new',     as: 'new_project'
  post   '/projects/create',  to: 'projects#create',  as: 'create_project'
  get    '/projects/edit',    to: 'projects#edit',    as: 'edit_project'
  patch  '/projects/update',  to: 'projects#update',  as: 'update_project'
  get    '/projects/destroy', to: 'projects#delete',  as: 'delete_this_project'
  delete '/projects/destroy', to: 'projects#destroy', as: 'destroy_project'
  get    '/projects/show/:id',to: 'projects#show',    as: 'show_project'
  
  get    '/projects/schedule',    to: 'projects#get_schedule',  as: 'get_schedule'
  get    '/projects/budget',      to: 'projects#get_budget',    as: 'get_budget'
  get    '/projects/add_member',  to: 'projects#assign_job',    as: 'assign_member_job'
  post   '/projects/add_member',  to: 'projects#add_member',    as: 'add_member_to_project'
  delete '/projects/lose_member', to: 'projects#remove_member', as: 'remove_member_from_project'
  root to: 'pages#home'

  get '/about', to: 'information#about'

  devise_for :users

  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end
  
  get '/user/:id', to: 'users#show', as: 'show_user'

end

=begin

  Lord of my life
  Here is my heart
  Been so good
  Fear is not my future
  You really are
  Costly
  One name
  Build your church
  More than Able
  Firm Foundation
  Jehovah
  Yahweh
  Yahweh will Manifest
  Yeshua
  Who is this man?
  Praise (Elevation)
  Welcome Resurrection (Elevation)
  Good (can't be anything else)
  Show me your Glory
  Crowned (highlands worship, Rebecca Hart)
  All hail the Power of Jesus name

=end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :milestone

  validates :name, presence: true, length: {minimum:  4, maximum:  40}

  has_many :sub_tasks, dependent: :destroy
  
  def update_complete
    return if self.sub_tasks.blank?
    sum = 0
    self.sub_tasks.each {|sub_task|
      sum += 1 if sub_task.complete == true
    }
    sum == self.sub_tasks.count ? self.complete = true : self.complete = false 
  end

  def expenses
    user = User.find(self.assigned_to)
    rate = user.hourly_rate
    day = self.start_date
    duration = 1
    (self.end_date - self.start_date).to_i.times do
      day += 1.day
      duration += 1 if day.on_weekday?      
    end
    hours = duration * 8
    return hours*rate
  end

  def self.day_options
    days = []
    31.times do |d|
      days.append(d+1)
    end
    days.to_a
  end

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map {|name, index| ["#{name}", index+1]}
  end

  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  $milestone_id = nil
  
  def new
    redirect_to root_path if !correct_project_leader?(params[:id].to_i)
    @task         = Task.new(milestone_id: params[:id].to_i)
    @milestone    = Milestone.find(@task.milestone_id)
    @project      = Project.find(@milestone.project_id)
    $milestone_id = params[:id].to_i
    @members = []
    members  = Project.find(Milestone.find(params[:id].to_i).project_id).members
    members.each { |m| @members.append(m.email) }
  end

  def create
    milestone = Milestone.find($milestone_id)
    task      = Task.new
    task.name = params[:task][:name]
    task.description = params[:task][:description]
    days = get_start_and_end_dates_parts
    start_day        = days[:start].join('/').to_date
    end_day          = days[:end].join('/').to_date
    
    if start_day >= milestone.start_date && start_day < milestone.end_date
      task.start_date          = start_day
      task.baseline_start_date = start_day
    else
      task.start_date          = milestone.start_date
      task.baseline_start_date = milestone.start_date 
    end

    if end_day   >  milestone.start_date && end_day <=  milestone.end_date
      task.end_date          = end_day
      task.baseline_end_date = end_day
    else
      task.end_date          = milestone.end_date
      task.baseline_end_date = milestone.end_date
    end

    task.milestone_id = milestone.id
    task.assigned_to  = User.where(email: params[:task][:assignee]).first.id

    if task.save
      flash[:notice] = 'Task created'
      update_milestone(milestone.id)
      notification   = Notification.new(project_id: milestone.project_id)
      notification.task_created_notification(task.name)
      notification.save
      redirect_to show_task_path(id: task.id)
    else
      flash[:alert]  = 'Something went wrong'
      render :new
    end

  end

  def edit
    @task = Task.find(params[:id].to_i)
    @milestone = Milestone.find(@task.milestone_id)
    @project   = Project.find(@milestone.project_id)
    $task_id   = params[:id].to_i
    @members = []
    members  = Project.find(Milestone.find(@task.milestone_id).project_id).members
    members.each { |m| @members.append(m.email) }
  end

  def update
    task = Task.find($task_id)
    task.name = params[:task][:name]
    task.description  = params[:task][:description]
    task.assigned_to  = User.where(email: params[:task][:assignee]).first.id if params[:task][:assignee] != "admin@admin.com"

    params[:task][:complete] == "true" ? task.complete = true : task.complete = false

    days = get_start_and_end_dates_parts
    start_day        = days[:start].join('/').to_date
    end_day          = days[:end].join('/').to_date

    if start_day >= task.baseline_start_date && start_day < task.baseline_end_date
      task.start_date = start_day
    end

    if (end_day > task.baseline_start_date && end_day <= task.baseline_end_date) 
      task.end_date = end_day
    end

    if task.save
      flash[:notice] = 'Task Updated'
      update_milestone(task.milestone_id)
      notification   = Notification.new(project_id: Milestone.find(task.milestone_id).project_id)
      notification.task_updated_notification(task.name)
      notification.save
      redirect_to show_task_path(id: task.id)
    else
      flash[:alert]  = 'Something went wrong'
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id].to_i)
    milestone = Milestone.find(@task.milestone_id)
    notification   = Notification.new(project_id: milestone.project_id)
    notification.task_deleted_notification(@task.name)
    notification.save
    @task.destroy
    flash[:notice] = 'Task Deleted'
    redirect_to show_milestone_path(id: milestone.id)
  end

  def show
    @task      = Task.find(params[:id])
    @sub_tasks = SubTask.where(task_id: @task.id).all
    @milestone = Milestone.find(@task.milestone_id)
    @project   = Project.find(@milestone.project_id)
  end

  private

  def correct_project_leader?(milestone_id)
    milestone = Milestone.find(milestone_id)
    project   = Project.find(milestone.project_id)
    current_user.id == project.leader
  end

  def get_start_and_end_dates_parts
    start_day_parts  = [ params[:task][:start_day], params[:task][:start_month], params[:task][:start_year] ]
    end_day_parts    = [ params[:task][:end_day],   params[:task][:end_month], params[:task][:end_year] ]
    {start: start_day_parts, end: end_day_parts}
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with model:@task, url: create_task_path do |t| %>
  <%= t.label :task_name %>
  <%= t.text_field :name, class:'form-control' %>

  <%= t.label :description %>
  <%= t.text_area :description, class:'form-control' %>
  <p class='mt-4'> <h5>Milestone dates: ( <%= @milestone.start_date%> - <%= @milestone.end_date %> ) </h5> </p>
  <div class='row'>
    <div class='col-6'>
      <p> <h4> <%= t.label :start_date %> </h4> </p>
      <%= t.select :start_day,   options_for_select(Task.day_options)   %>
      <%= t.select :start_month, options_for_select(Task.month_options) %>
      <%= t.select :start_year,  options_for_select(Task.year_options)  %>
    </div>
    <div class='col-6'>
      <p> <h4> <%= t.label :end_date %> </h4> </p>
      <%= t.select :end_day,   options_for_select(Task.day_options)   %>
      <%= t.select :end_month, options_for_select(Task.month_options) %>
      <%= t.select :end_year,  options_for_select(Task.year_options)  %>
    </div>

  <% if !@task.new_record? && @task.sub_tasks.blank?%>
    <p>
    <%= t.check_box :complete, {}, true, false %>
    <%= t.label :complete? %>
    </p>
  <% end %>
  </div>
  <div class='col-6'>
    <p> <h4> <%= t.label :Assignee %> </h4> </p>
    <%= t.select :assignee, options_for_select(@members) %>
  </div>
  <p> <%= t.submit(@task.new_record? ? "Create Task" : "Update Task", class:'btn mt-4', style:'color: white; background-color: #5c0101')%> </p>
<% end %>
<p> <%= link_to "Cancel", show_milestone_path(id: @task.milestone), class:'btn btn-secondary' %> </p>

app/views/tasks/_page_topper.html.erb
<p>
  <small>
    <small>
      <%= link_to @project.name, show_project_path(id: @project.id), style:'color:white; text-decoration: none' %> >> 
      <%= link_to @milestone.name, show_milestone_path(id: @milestone.id), style:'color: white; text-decoration: none' %> >> 
      <% if @task.present? %>
      <%= @task.name %>
      <% end %>
    </small>
  </small>
</p>

app/views/tasks/_sub_tasks_list.html.erb
<table class="table" style='color:white'>
  <thead>
    <tr>
      <th scope="col"> <%= @task.name %> </th>
      <th scope="col"> Description </th>
    </tr>
  </thead>
  <tbody>
    <% @sub_tasks.each do |st| %>
      <tr>
        <% if st.complete %>
          <td> <%= link_to st.name, show_sub_task_path(id: st.id), style:'color: #29d916; text-decoration: none' %></td>
        <% else %>
          <td> <%= link_to st.name, show_sub_task_path(id: st.id), style:'color: red; text-decoration: none' %></td>
        <% end %>
        <td> <%= st.description.truncate(40) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<%= render 'page_topper' %>

<div class='row' style='padding-top:30px'>
  <div class='col-4'></div>
    <div class='col-md-4'>
      <h1>Edit Task</h1>
      <%= render 'form' %>
    </div>
  </div>
  <%= link_to "Delete Task", destroy_task_path(id: @task.id), data:{turbo_method: :delete, turbo_confirm: "Delete #{@task.name}"},class:'btn', style:'color:white; background-color: red'  %>
</div>

 

app/views/tasks/new.html.erb
<div class='row' style='padding-top:30px'>
  <div class='col-4'></div>
    <div class='col-md-4'>
    <h1>New Task</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<%= render 'page_topper' %>

 <div class="col-md-10" style='margin-left:30px'>
  <p> <h3> <%= @task.name %> </h3> </p>
  <div class='row', style='padding-bottom:20px; text-align:justify'>
    <div class='col-md-6' >
      <h4>Task:            <%= @task.name %> </h4>
      <p> Description:</p> <%= @task.description %>
    </div>
  </div>
  <% if @project.leader == current_user.id %>
    <%= link_to "Edit Task", edit_task_path(id: @task.id), class:'btn show_button'%>
  <% end %>
  <hr>
  <div class='row' style='margin-left:0px'>
    Sub-Tasks List
    <%= render 'sub_tasks_list' %>
  </div>
  <% if @project.leader == current_user.id || @task.assigned_to == current_user.id %>
    <%= link_to "New Sub-Task", new_sub_task_path(id: @task.id), class:'btn mt-4 mb-4 show_button' %>
  <% end %>
</div> 