config/routes.rb
Rails.application.routes.draw do
  get    '/notifications/list',    to: 'notifications#list',    as: 'list_notifications'

  resources :sub_tasks, except: [:new, :edit, :destroy, :show]
  get    '/sub_tasks/new',     to: 'sub_tasks#new',     as: 'new_sub_task'
  get    '/sub_tasks/show',    to: 'sub_tasks#show',    as: 'show_sub_task'
  post   '/sub_tasks/create',  to: 'sub_tasks#create',  as: 'create_sub_task'
  get    '/sub_tasks/edit',    to: 'sub_tasks#edit',    as: 'edit_sub_task'
  patch  '/sub_tasks/update',  to: 'sub_tasks#update',  as: 'update_sub_task'
  delete '/sub_tasks/destroy', to: 'sub_tasks#destroy', as: 'destroy_sub_task'
  
  resources :tasks, except: [:new, :edit, :destroy, :show]
  get    '/tasks/new',     to: 'tasks#new',     as: 'new_task'
  post   '/tasks/create',  to: 'tasks#create',  as: 'create_task'
  get    '/tasks/edit',    to: 'tasks#edit',    as: 'edit_task'
  patch  '/tasks/update',  to: 'tasks#update',  as: 'update_task'
  delete '/tasks/destroy', to: 'tasks#destroy', as: 'destroy_task'
  get    '/tasks/show',    to: 'tasks#show',    as: 'show_task'
  
  resources :milestones, except: [:new, :edit, :destroy, :show]
  get    '/milestones/new',     to: 'milestones#new',     as: 'new_milestone'
  get    '/milestones/show',    to: 'milestones#show',    as: 'show_milestone'
  post   '/milestones/create',  to: 'milestones#create',  as: 'create_milestone'
  get    '/milestones/edit',    to: 'milestones#edit',    as: 'edit_milestone'
  patch  '/milestones/update',  to: 'milestones#update',  as: 'update_milestone'
  delete '/milestones/destroy', to: 'milestones#destroy', as: 'destroy_milestone'

  resources :projects, except: [:new, :edit, :destroy, :show]
  get    '/projects/new',     to: 'projects#new',     as: 'new_project'
  post   '/projects/create',  to: 'projects#create',  as: 'create_project'
  get    '/projects/edit',    to: 'projects#edit',    as: 'edit_project'
  patch  '/projects/update',  to: 'projects#update',  as: 'update_project'
  get    '/projects/destroy', to: 'projects#delete',  as: 'delete_this_project'
  delete '/projects/destroy', to: 'projects#destroy', as: 'destroy_project'
  get    '/projects/show/:id',to: 'projects#show',    as: 'show_project'
  
  get    '/projects/schedule',    to: 'projects#get_schedule',  as: 'get_schedule'
  get    '/projects/budget',      to: 'projects#get_budget',    as: 'get_budget'
  get    '/projects/add_member',  to: 'projects#assign_job',    as: 'assign_member_job'
  post   '/projects/add_member',  to: 'projects#add_member',    as: 'add_member_to_project'
  delete '/projects/lose_member', to: 'projects#remove_member', as: 'remove_member_from_project'
  root to: 'pages#home'

  get '/about', to: 'information#about'

  devise_for :users

  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end
  
  get '/user/:id', to: 'users#show', as: 'show_user'

end

=begin

  Lord of my life
  Here is my heart
  Been so good
  Fear is not my future
  You really are
  Costly
  One name
  Build your church
  More than Able
  Firm Foundation
  Jehovah
  Yahweh
  Yahweh will Manifest
  Yeshua
  Who is this man?
  Praise (Elevation)
  Welcome Resurrection (Elevation)
  Good (can't be anything else)
  Show me your Glory
  Crowned (highlands worship, Rebecca Hart)
  All hail the Power of Jesus name

=end

app/models/sub_task.rb
class SubTask < ApplicationRecord
  belongs_to :task
end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  $task_id = nil

  def new
    @sub_task  = SubTask.new
    @task      = Task.find(params[:id].to_i)
    @milestone = Milestone.find(@task.milestone_id)
    @project   = Project.find(@milestone.project_id)
    $task_id   = params[:id].to_i
  end

  def create
    sub_task = SubTask.new
    
    sub_task.task_id     = $task_id
    sub_task.name        = params[:sub_task][:name]
    sub_task.description = params[:sub_task][:description]
    
    if sub_task.save
      flash[:notice] = 'Created Sub-Task'
      update_task(Task.find(sub_task.task_id).id)
      redirect_to show_sub_task_path(id: sub_task.id)
    else
      flash[:notice] = 'Something went wrong'
      redirect_to new_sub_task_path(id: sub_task.task_id)
    end
  end

  def edit
    @sub_task  = SubTask.find(params[:id].to_i)
    @task      = Task.find(@sub_task.task_id)
    @milestone = Milestone.find(@task.milestone_id)
    @project   = Project.find(@milestone.project_id)   
  end

  def update
    sub_task = SubTask.find(params[:id])
    sub_task.name        = params[:sub_task][:name]
    sub_task.description = params[:sub_task][:description]
    params[:sub_task][:complete] == "0" ? sub_task.complete = false : sub_task.complete = true
    if sub_task.save
      flash[:notice] = 'Sub-Task Updated'
      update_task(Task.find(sub_task.task_id).id)
      redirect_to show_sub_task_path(id: sub_task.id)
    else
      flash[:alert] = 'Something went wrong'
      redirect_to edit_sub_task_path(id: sub_task.id)
    end
  end

  def destroy 
    @sub_task = SubTask.find(params[:id])
    @task     = Task.find(@sub_task.task_id)
    @sub_task.destroy
    flash[:notice] = 'Successfully deleted sub_task'
    redirect_to show_task_path(id: @task.id)
  end

  def show
    @sub_task  = SubTask.find(params[:id])
    @task      = Task.find(@sub_task.task_id)
    @milestone = Milestone.find(@task.milestone_id)
    @project   = Project.find(@milestone.project_id)    
  end

  private

  def sub_task_params
    params.require('sub_task').permit(:name, :description, :complete)
  end

end

app/helpers/sub_tasks_helper.rb
module SubTasksHelper
end

app/views/sub_tasks/_form.html.erb
<%= form_with model: @sub_task, local: true do |st| %>
  <%= st.label :name %>
  <%= st.text_field :name, class:'form-control' %>

  <%= st.label :description %>
  <%= st.text_area :description, class:'form-control mb-3' %>

  <% if !@sub_task.new_record? %>
    <p class='mt-3'>
      <%= st.check_box :complete, {}, [true, false]%>
      <%= st.label :complete %>
    </p>
  <% end %>
  
  <%= st.submit(@sub_task.new_record? ? "Create Sub-Task" : "Update Sub-Task", class:'btn', style:'color: white; background-color: #5c0101')%>
<% end %>

<%= link_to "Cancel", show_task_path(id: @task.id), class:'btn btn-secondary mt-3' %>

app/views/sub_tasks/_page_topper.html.erb
<p>
  <small>
    <small>
      <%= link_to @project.name, show_project_path(id: @project.id), style:'color:white; text-decoration: none' %> >> 
      <%= link_to @milestone.name, show_milestone_path(id: @milestone.id), style:'color: white; text-decoration: none' %> >> 
      <%= link_to @task.name, show_task_path(id: @task.id), style:'color: white; text-decoration: none' %> >> 
      <% if @sub_task.present? %>
        <%= @sub_task.name %>
      <% end %>
    </small>
  </small>
</p>

app/views/sub_tasks/edit.html.erb
<%= render 'page_topper' %>

<div class='row' style='padding-top:30px'>
  <div class='col-4'></div>
    <div class='col-md-4'>
      <h1>Edit Sub-Task</h1>
      <%= render 'form' %>
    </div>
  </div>
  <%= link_to "Delete Sub Task", destroy_sub_task_path(id: @sub_task.id), data:{turbo_method: :delete, turbo_confirm: "Delete #{@sub_task.name}"},
  class:'btn', style:'color:white; background-color: red' %>
</div> 

app/views/sub_tasks/new.html.erb
<%= render 'page_topper' %>

<div class='row' style='padding-top:30px'>
  <div class='col-4'></div>
    <div class='col-md-4'>
      <h1>New Sub-Task</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/sub_tasks/show.html.erb
<%= render 'page_topper' %>

 <div style='margin-left:30px'>
  <p> <h3> <%= @sub_task.name %> </h3> </p>
  <div class='row', style='padding-bottom:20px; text-align:justify'>
    <div class='col-md-6' >
      <p> <strong> Description: </strong> </p> <p style='padding-left:20px'><%= @sub_task.description %> </p>
    </div>
  </div>
  <% if @project.leader == current_user.id %>
    <%= link_to "Edit Sub-Task", edit_sub_task_path(id: @sub_task.id), class:'btn show_button'%>
  <% end %>
  <hr class='col-md-11'>
</div> 