config/routes.rb
Rails.application.routes.draw do
  get    '/notifications/list',    to: 'notifications#list',    as: 'list_notifications'

  resources :sub_tasks, except: [:new, :edit, :destroy, :show]
  get    '/sub_tasks/new',     to: 'sub_tasks#new',     as: 'new_sub_task'
  get    '/sub_tasks/show',    to: 'sub_tasks#show',    as: 'show_sub_task'
  post   '/sub_tasks/create',  to: 'sub_tasks#create',  as: 'create_sub_task'
  get    '/sub_tasks/edit',    to: 'sub_tasks#edit',    as: 'edit_sub_task'
  patch  '/sub_tasks/update',  to: 'sub_tasks#update',  as: 'update_sub_task'
  delete '/sub_tasks/destroy', to: 'sub_tasks#destroy', as: 'destroy_sub_task'
  
  resources :tasks, except: [:new, :edit, :destroy, :show]
  get    '/tasks/new',     to: 'tasks#new',     as: 'new_task'
  post   '/tasks/create',  to: 'tasks#create',  as: 'create_task'
  get    '/tasks/edit',    to: 'tasks#edit',    as: 'edit_task'
  patch  '/tasks/update',  to: 'tasks#update',  as: 'update_task'
  delete '/tasks/destroy', to: 'tasks#destroy', as: 'destroy_task'
  get    '/tasks/show',    to: 'tasks#show',    as: 'show_task'
  
  resources :milestones, except: [:new, :edit, :destroy, :show]
  get    '/milestones/new',     to: 'milestones#new',     as: 'new_milestone'
  get    '/milestones/show',    to: 'milestones#show',    as: 'show_milestone'
  post   '/milestones/create',  to: 'milestones#create',  as: 'create_milestone'
  get    '/milestones/edit',    to: 'milestones#edit',    as: 'edit_milestone'
  patch  '/milestones/update',  to: 'milestones#update',  as: 'update_milestone'
  delete '/milestones/destroy', to: 'milestones#destroy', as: 'destroy_milestone'

  resources :projects, except: [:new, :edit, :destroy, :show]
  get    '/projects/new',     to: 'projects#new',     as: 'new_project'
  post   '/projects/create',  to: 'projects#create',  as: 'create_project'
  get    '/projects/edit',    to: 'projects#edit',    as: 'edit_project'
  patch  '/projects/update',  to: 'projects#update',  as: 'update_project'
  get    '/projects/destroy', to: 'projects#delete',  as: 'delete_this_project'
  delete '/projects/destroy', to: 'projects#destroy', as: 'destroy_project'
  get    '/projects/show/:id',to: 'projects#show',    as: 'show_project'
  
  get    '/projects/schedule',    to: 'projects#get_schedule',  as: 'get_schedule'
  get    '/projects/budget',      to: 'projects#get_budget',    as: 'get_budget'
  get    '/projects/add_member',  to: 'projects#assign_job',    as: 'assign_member_job'
  post   '/projects/add_member',  to: 'projects#add_member',    as: 'add_member_to_project'
  delete '/projects/lose_member', to: 'projects#remove_member', as: 'remove_member_from_project'
  root to: 'pages#home'

  get '/about', to: 'information#about'

  devise_for :users

  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end
  
  get '/user/:id', to: 'users#show', as: 'show_user'

end

=begin

  Lord of my life
  Here is my heart
  Been so good
  Fear is not my future
  You really are
  Costly
  One name
  Build your church
  More than Able
  Firm Foundation
  Jehovah
  Yahweh
  Yahweh will Manifest
  Yeshua
  Who is this man?
  Praise (Elevation)
  Welcome Resurrection (Elevation)
  Good (can't be anything else)
  Show me your Glory
  Crowned (highlands worship, Rebecca Hart)
  All hail the Power of Jesus name

=end

app/models/project.rb
class Project < ApplicationRecord

  after_create_commit { broadcast_append_to "projects" }
  
  has_many_attached :attachments, dependent: :destroy

  has_many :milestones, dependent: :destroy

  has_many :notifications, dependent: :destroy

  def expenses
    expenses   = 0
    milestones = self.milestones
    milestones.each {|milestone|
      tasks = milestone.tasks
      tasks.each {|task|
        duration = 1
        day      = task.start_date
        (task.end_date - task.start_date).to_i.times do
          day      += 1.day
          duration += 1 if day.on_weekday?
        end
        hours_worked = duration * 8
        hourly_rate  = User.find(task.assigned_to).hourly_rate
        expenses    += hours_worked * hourly_rate
      }
    }
    self.expenses = expenses
  end

  def update_percent_complete
    sum = 0
    num = 0
    self.milestones.each {|milestone| 
      milestone.tasks.each{|task|
        sum += 100 if task.complete == true
        num += 1
      }
    }
    self.percent_complete = sum.to_f/num 
  end

  def members
    members = []
    User.all.each{|u|
      members.append(u) if Participant.where(user_id: u.id).all.where(project_id: self.id).present?
    }
    members
  end

  def non_members
    non_members = []
    User.all.each{|u|
      non_members.append(u) if Participant.where(user_id: u.id).all.where(project_id: self.id).blank?
    }
    non_members
  end

  def self.day_options
    days = []
    31.times do |d|
      days.append(d+1)
    end
    days.to_a
  end

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map {|name, index| ["#{name}", index+1]}
  end

  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :logged_in_only
  before_action :project_leaders_only, only: [:edit, :delete, :add_member, :remove_member]
  $proj_id = nil
  $user_id = nil

  def new
    @project  = Project.new
    @users    = User.all_except(current_user)
  end

  def create
    project = Project.new
    project.description = params[:project][:description]
    project.attachments = params[:project][:attachments] if params[:project][:attachments].present?
    project.name   = params[:project][:name]    
    project.budget = params[:project][:budget]
    start_parts    = [params[:project][:start_year],params[:project][:start_month],params[:project][:start_day]]
    project.start_date          = start_parts.join('/').to_date
    project.baseline_start_date = start_parts.join('/').to_date
    end_parts      = [params[:project][:end_year],params[:project][:end_month],params[:project][:end_day]]
    project.end_date          = end_parts.join('/').to_date
    project.baseline_end_date = end_parts.join('/').to_date
    project.leader = current_user.id
    if project.save
      flash[:notice] = 'Project successfully created'
      participant = Participant.new
      participant.user_id = current_user.id
      participant.project_id = project.id
      participant.save
      notification = Notification.new(project_id: project.id)
      notification.project_created_notification
      notification.save
      redirect_to show_project_path(id: project.id)
    else
      flash[:alert]  = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
    @users   = User.all_except(current_user)
    $proj_id = params[:id].to_i
    @members = @project.members
    @non_members = @project.non_members
    @milestones = Milestone.all.where(project_id: @project.id)
  end

  def assign_job
    @user    = User.find(params[:id].to_i)
    @project = Project.find($proj_id)
    $user_id = params[:id].to_i
  end

  def add_member
    return if Project.find($proj_id).leader != current_user.id
    user        = User.find($user_id)
    user.job    = params[:user][:job]
    user.set_hourly_rate
    participant = Participant.new
    participant.user_id    = $user_id
    participant.project_id = $proj_id

    if participant.save
      flash[:notice] = "Added member to project"
      if user.save
        notification   = Notification.new(project_id: $proj_id)
        notification.member_added_notification(user.email)
        notification.save
        flash[:notice] = "Assigned #{user.email} job"
      end
    else
      flash[:alert]  = "Something went wrong"
    end
    redirect_to show_project_path(id: $proj_id)
  end

  def remove_member
    return if Project.find($proj_id).leader != current_user.id
    user = User.find(params[:id].to_i)
    user.job = "unemployed"
    user.set_hourly_rate
    user.save
    @participant = Participant.where(user_id: user.id, project_id: $proj_id).first
    if user.id != Project.find($proj_id).leader
      notification   = Notification.new(project_id: $proj_id)
      notification.member_removed_notification(user.email)
      notification.save
      @participant.destroy
      flash[:notice] = "Removed member to project"
    end
    redirect_to show_project_path(id: $proj_id) 
  end

  def edit
    @project = Project.find(params[:id])
    @users   = User.all_except(current_user)
    $proj_id = params[:id].to_i
  end

  def update
    project = Project.find($proj_id)
    project.description = params[:project][:description]
    project.name        = params[:project][:name]    
    project.budget      = params[:project][:budget]
    start_parts         = [params[:project][:start_year],params[:project][:start_month],params[:project][:start_day]]
    project.start_date  = start_parts.join('/').to_date if start_parts.join('/').to_date > project.start_date
    end_parts           = [params[:project][:end_year],params[:project][:end_month],params[:project][:end_day]]
    project.end_date    = end_parts.join('/').to_date   if end_parts.join('/').to_date > project.start_date
    if project.save
      flash[:notice] = 'Project successfully updated'
      check_end_dates(project.id)
      notification = Notification.new(project_id: project.id)
      notification.project_edited_notification
      notification.save
      redirect_to show_project_path(id: project.id)
    else
      flash[:alert]  = 'Something went wrong'
      render 'new'
    end
    
  end

  def delete
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = 'Project Successfully Destroyed'
  end

  def get_schedule
    @project = Project.find(params[:id])
    redirect_to show_project_path(id: @project.id) if @project.leader != current_user.id
    @milestones = @project.milestones
    @tasks = []
    @milestones.each {|milestone| @tasks.append(milestone.tasks) }
    today = Date.today
    @time_completed     = (today - @project.start_date)/(@project.end_date - @project.start_date).to_f * 100
    rate_of_work        = @project.percent_complete.to_f / @time_completed
    days_left           = (@project.end_date - today).to_f / rate_of_work
    @predicted_end_date = today + days_left
  end

  def get_budget
    @project  = Project.find(params[:id])
    redirect_to show_project_path(id: @project.id) if @project.leader != current_user.id
    @milestones = @project.milestones
    @milestone_expenses = []
    @task_expenses      = []
    @tasks = []
    @all_expenses = []
    @milestones.each {|milestone|
      @milestone_expenses.append(milestone.expenses)
      @all_expenses.append({milestone: milestone.name, 
        expense: number_to_currency(milestone.expenses, :unit=>'R ', :separator=>',', :delimiter=>' '), 
        budget:  number_to_currency(milestone.budget,   :unit=>'R ', :separator=>',', :delimiter=>' ')})
      @tasks.append(milestone.tasks)
      milestone.tasks.each {|task|
        @task_expenses.append(task.expenses)
        @all_expenses.append({task: task.name, expense: number_to_currency(task.expenses, :unit=>'', :separator=>',', :delimiter=>' ')})
      }
    }
    @project_expenses   = number_to_currency(@project.expenses, :unit=>'R ')
    @project.save
  end

  private

  def project_leaders_only
    redirect_to show_project_path(id: $proj_id), alert: 'Project leaders only.' if current_user.role != "leader"
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with model:@project, url: create_project_path do |f| %>
  <h5 class='mt-4'><%= f.label  :project_leader%></h5>
  <%= f.text_field :name, placeholder:"#{current_user.email}", class:'form-control disabled-field'%>
  <h5 class='mt-4'><%= f.label  :project_name%></h5>
  <%= f.text_field :name, class:'form-control' %>
  <h5 class='mt-4'><%= f.label  :project_description%></h5>
  <%= f.text_area  :description, class:'form-control'%>
  <div class='row'>
    <div class='col-6'>
      <h5 class='mt-4'><%= f.label :start_date%> </h5>
      <%= f.select :start_year,  options_for_select(Project.year_options) %>
      <%= f.select :start_month, options_for_select(Project.month_options) %>
      <%= f.select :start_day,   options_for_select(Project.day_options) %>
    </div>
    <div class='col-6'>
      <h5 class='mt-4'><%= f.label :end_date%> </h5>
      <%= f.select :end_year,  options_for_select(Project.year_options) %>
      <%= f.select :end_month, options_for_select(Project.month_options) %>
      <%= f.select :end_day,   options_for_select(Project.day_options) %>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-6'>
      <h5 class='mt-4'><%= f.label :Budget %> (ZAR) </h5>
      <%= f.number_field :budget, in: 5000.0..500000.0, step: 5000.0, class:'form-control disabled'%>
    </div>
    <div class='col-6'>
      <h5 class='mt-4'><%= f.label :project_files %></h5>
      <%= f.file_field(:attachments, multiple: true)%>  
    </div>
  </div>
  <%= f.submit(@project.new_record? ? "Create Project" : "Update Project", data:{turbo: false}, class:'btn mt-4', style:'background-color: #5c0101 ; color: white') %>
<% end %>
<%= link_to "Cancel", ( @project.new_record? ? root_path : show_project_path(id: @project.id) ), class:'btn btn-secondary mt-4 mb-4' %>

app/views/projects/_gantt_chart.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'https://cdn.dhtmlx.com/gantt/edge/dhtmlxgantt.css' %>
  <%= javascript_include_tag 'https://cdn.dhtmlx.com/gantt/edge/dhtmlxgantt.js' %>
<% end %>

<div id="gantt_here" style="width:100%; height:800px"></div>

<script>
  gantt.init("gantt_here")
</script>

app/views/projects/_project.html.erb
<p>
  <%= link_to show_project_path(id: project.id), style:'text-decoration: none; color: white' do %>
    <%= fa_icon "gg"%>
    <%= project.name %>
  <% end %>
</p> 

app/views/projects/assign_job.html.erb
<div style='margin-left:30px'>
  <p> <h4> Assign <%= @user.email %> job </h4> </p>
  <div class='row', style='padding-bottom:20px; text-align:justify'>
    <div class='col-md-6' >
    <%= form_with model:@user, url: add_member_to_project_path, method: :post do |f| %>
      <div class='field'>
        <h5><%= f.label  :job %> </h5> 
        <%= f.select :job, options_for_select(User.job_options) %>
      </div>
      <%= f.submit "Add member", data:{turbo_confirm: "Assign #{@user.email} this job?"}, class:'btn mt-4 mb-4', style:'color:white; background-color: #5c0101'%>
    <% end %>
    <%= link_to "Cancel", show_project_path(id: @project.id), class:'btn btn-secondary' %>
  </div>
</div>

app/views/projects/delete.html.erb
<div class='row' style='padding-top:20px'>
  <div class='col-1'></div>
    <div class='col-md-4'>

      <h2>Delete <%= @project.name %>? </h2>

      <h4 class='mt-4 mb-4'> Project deletion is irreversible </h4>

      <%= link_to "Delete Project", destroy_project_path(id: @project.id), data:{turbo_method: :delete, turbo_confirm: "Are you Sure?"}, class:'btn btn-danger' %>

    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class='row' style='padding-top:30px'>
  <div class='col-4'></div>
    <div class='col-md-4'>
    <h1>Edit Project: <%= @project.name %> </h1>
      <%= render 'form' %>
    </div>
  </div>
  <% if @project.leader == current_user.id %>
    <%= link_to "Delete Project", delete_this_project_path(id: @project.id), class:'btn', style:'width:200px; color:white; background-color: red ' %>
  <% end %>
</div>

app/views/projects/get_budget.html.erb
<h3> <%= @project.name %> Budget </h3>

<div class='row d-flex justify-content-center' style='padding-top:30px'>
  <div class='col-md-10'>
    <table class="table" style="color:white">
      <thead>
        <tr>      
          <th scope="col"></th>
          <th scope="col"><h4> PM-Tool         </h4></th>
          <th scope="col"><h4> Baseline Budget </h4></th>
          <th scope="col"><h4> Actual Budget   </h4></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"></th>
          <td> <h5> <%= @project.name %> </h5> </td>
          <td> <h5> <%= number_to_currency(@project.budget, :unit=>'R ') %> </h5> </td>
          <% if @project.expenses < @project.budget %>
            <td> <h5 style="color:green"> <%= number_to_currency(@project.expenses, :unit=>'R ') %> </h5> </td>
          <% else %>
            <td> <h5 style="color:red">   <%= number_to_currency(@project.expenses, :unit=>'R ') %> </h5> </td>
          <% end %>
        </tr>
        <% @all_expenses.each do |instance| %>
          <tr>
            <th scope="row"></th>
            <% if instance[:milestone].present? %>
              <td style="padding-left:35px"> <h6> <%= instance[:milestone] %> </h6> </td>
              <td> <h6> <%= instance[:budget] %> </h6> </td>
              <td> <h6> <%= instance[:expense] %> </h6> </td>
            <% elsif instance[:task].present? %>
              <td style="padding-left:70px"> <%= instance[:task] %> </td>
              <td>  </td>
              <td> <%= instance[:expense] %> </td>
            <% end %>            
          </tr>
        <% end %>
      </tbody>
    </table>

    <div>
      <% if @project.expenses > @project.budget     %>
        <p style='color:red'> Project is over budget </p>
      <% elsif @project.expenses < @project.budget  %>
        <p style='color:green'> Project is under budget </p>
      <% end %>
    </div>

  </div>
</div>

app/views/projects/get_schedule.html.erb
<h3> <%= @project.name %> schedule </h3>

<div class='row d-flex justify-content-center' style='padding-top:30px'>
  <div class='col-md-10'>
    <table class="table" style="color:white">
      <thead>
        <tr>      
          <th scope="col"></th>
          <th scope="col"><h4> PM-Tool             </h4></th>
          <th scope="col"><h4> Baseline Start Date </h4></th>
          <th scope="col"><h4> Start Date          </h4></th>
          <th scope="col"><h4> Baseline End Date   </h4></th>
          <th scope="col"><h4> End Date            </h4></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"></th>
          <td> <h5> <%= @project.name %> </h5> </td>
          <td> <%= @project.baseline_start_date %> </td>
          <td> <%= @project.start_date %>          </td>
          <td> <%= @project.baseline_end_date %>   </td>
          <td> <%= @project.end_date %>            </td>
        </tr>
        <% @milestones.each do |milestone| %>
          <tr>
            <th scope="row"></th>
            <td style="padding-left:35px"> <h6> <%= milestone.name %> </h6> </td>
            <td> <%= milestone.baseline_start_date %> </td>
            <td> <% if milestone.baseline_start_date != milestone.start_date %> <%= milestone.start_date %> <% end %> </td>
            <td> <%= milestone.baseline_end_date %>   </td>
            <td> <% if milestone.baseline_end_date != milestone.end_date %>     <%= milestone.end_date %>   <% end %> </td> 
          </tr>
          <% milestone.tasks.each do |task| %>
            <tr>
              <th scope="row"></th>
              <td style="padding-left:70px"> <%= task.name %>       </td>
              <td> <%= task.baseline_start_date %> </td>
              <td> <% if task.baseline_start_date != task.start_date %> <%= task.start_date %> <%else%> baseline <%end%> </td>
              <td> <%= task.baseline_end_date %>   </td>
              <td> <% if task.baseline_end_date != task.end_date %>     <%= task.end_date %>   <%else%> baseline <%end%> </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <div>
      <% if @time_completed.round(0) > @project.percent_complete     %>
        <p> Project is behind schedule </p>
      <% elsif @time_completed.round(0) == @project.percent_complete %>
        <p> Project is just about on schedule </p>
      <% elsif @time_completed.round(0) < @project.percent_complete  %>
        <p> Project is ahead of schedule </p>
      <% end %>
      <p> Project predicted to end on <%= @predicted_end_date %> </p>
    </div>

  </div>
</div>

app/views/projects/new.html.erb
<div class='row' style='padding-top:30px'>
  <div class='col-4'></div>
    <div class='col-md-4'>
    <h1>New Project</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div style='margin-left:30px'>
  <p> <h3> <%= @project.name %> </h3> </p>
  <div class='row', style='padding-bottom:20px; text-align:justify'>
    <div class='col-md-6' >
      <p><strong> <%= @project.percent_complete %> % complete </strong></p>
      <p><strong>Description:</strong> </p><p style='padding-left:20px'> <%= @project.description %></p>
      <p><strong>Start date:</strong>      <%= @project.baseline_start_date %></p>
      <p><strong>End date:</strong>        <%= @project.baseline_end_date %> </p>
      <p><strong>Project leader:</strong>  <%= User.find(@project.leader).email %> </p>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-3'>
      <div class='collapsible col-md-12' id="collapsible">
        <input type='checkbox' id="collapsible2-head-members">
        <label for="collapsible2-head-members" style='color: white'> Members </label>
        <div class="collapsible-text">
          <% @members.each do |m|%>
            <p>
              <%= link_to remove_member_from_project_path(id: m.id), data:{turbo_method: :delete, turbo_confirm: "Remove #{m.email} from Project?"}, style:'text-decoration: none; color: #40c92e' do %>
                <%= fa_icon "minus-square-o", style:'color:red' %>
                <%= fa_icon "user" %>
              <% end %>
              <%= link_to m.email, show_user_path(id: m.id), style:'text-decoration: none; color: #40c92e' %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <div class='col-md-1'></div>
    <div class='col-md-3'>
      <% if @project.leader == current_user.id %>
        <div class='collapsible col-md-12' id="collapsible">
          <input type='checkbox' id="collapsible2-head-nonmembers">
          <label for="collapsible2-head-nonmembers" style='color: white'> Non-Members </label>
          <div class="collapsible-text">
            <% if @non_members.blank? %>
              <p> No Non-members </p>
            <% end %>
            <% @non_members.each do |nm|%>
              <p>
                <%= link_to assign_member_job_path(id: nm.id), style:'text-decoration: none; color: #3b7cd1' do %>
                  <%= fa_icon "plus-square-o", style:'color:#40c92e' %>
                  <%= fa_icon "user"%>
                <% end %>
                <%= link_to nm.email, show_user_path(id: nm.id), style:'text-decoration: none; color: #40c92e' %>
              </p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <% if @project.attachments.attached? && @members.include?(current_user)%>
    <h4 style='padding-top:30px'> Project Documents </h4>
    <% @project.attachments.each_with_index do |attachment, index| %>
      <p style='padding:10px'>
        <%= link_to url_for(attachment), style:'text-decoration: none; color: white' do %>
          <%= fa_icon 'file-o' %>
          <%= attachment.filename %>
        <% end %>
      </p>
    <% end %>
  <% end %>
  
  <% if @project.leader == current_user.id %>
    <%= link_to "Edit Project", edit_project_path(id: @project.id), class:'btn mt-4 show_button' %>
    <%= link_to "Project Schedule", get_schedule_path(id: @project.id), class:'btn mt-4 show_button' %>
    <%= link_to "Project Budget",   get_budget_path(id: @project.id), class:'btn mt-4 show_button' %>
  <% end %>
  <hr class='col-11'>

  <% if @members.include?(current_user) %>
    <h4>Milestones</h4>
    <% if @milestones.present? %>
      <div class='row'>
        <% @milestones.each do |milestone| %>
          <div class='big-block col-md-3 mb-4' style='margin-right:30px;'>
            <p> <h5> <%= link_to milestone.name, show_milestone_path(id: milestone.id), class:'show_button', style:' text-decoration:none' %> </h5> </p>
            <p> <h6> <%= milestone.completion %> % </h6> </p>
            <p> Description:  </p> <%= milestone.description %>
          </div>
        <% end %>
      </div>
    <% end %>
    <% if @project.leader == current_user.id %>
      <%= link_to "New Milestone", new_milestone_path(id: @project.id), class:'btn mt-4 show_button' %>
    <% end %>
  <% end %>
</div>